/**
 * ReportGeneratorService - Domain Service
 * 
 * Generates PDF and Excel compliance reports with annotated photos.
 */

export interface InspectionReportData {
    siteId: string;
    siteName: string;
    inspectorName: string;
    inspectionDate: Date;
    weatherConditions: string;
    findings: InspectionFinding[];
    overallCompliance: boolean;
    riskScore?: number;
}

export interface InspectionFinding {
    bmpType: string;
    condition: 'good' | 'fair' | 'poor' | 'critical';
    photoUrl?: string;
    defects: string[];
    recommendedAction?: string;
    coordinates?: { latitude: number; longitude: number };
}

export interface GeneratedReport {
    id: string;
    format: 'pdf' | 'excel';
    filename: string;
    contentBase64: string;
    generatedAt: Date;
    sizeBytes: number;
}

export class ReportGeneratorService {
    /**
     * Generate a PDF inspection report
     */
    async generatePdfReport(data: InspectionReportData): Promise<GeneratedReport> {
        const reportContent = this.buildReportHtml(data);
        const base64Content = Buffer.from(reportContent).toString('base64');

        return {
            id: crypto.randomUUID(),
            format: 'pdf',
            filename: this.generateFilename(data, 'pdf'),
            contentBase64: base64Content,
            generatedAt: new Date(),
            sizeBytes: base64Content.length,
        };
    }

    /**
     * Generate an Excel inspection report
     */
    async generateExcelReport(data: InspectionReportData): Promise<GeneratedReport> {
        const csvContent = this.buildCsvContent(data);
        const base64Content = Buffer.from(csvContent).toString('base64');

        return {
            id: crypto.randomUUID(),
            format: 'excel',
            filename: this.generateFilename(data, 'xlsx'),
            contentBase64: base64Content,
            generatedAt: new Date(),
            sizeBytes: base64Content.length,
        };
    }

    /**
     * Generate filename based on site and date
     */
    private generateFilename(data: InspectionReportData, extension: string): string {
        const dateStr = data.inspectionDate.toISOString().split('T')[0];
        const siteName = data.siteName.replace(/[^a-zA-Z0-9]/g, '_');
        return `${siteName}_Inspection_${dateStr}.${extension}`;
    }

    /**
     * Build HTML content for PDF
     */
    private buildReportHtml(data: InspectionReportData): string {
        const complianceStatus = data.overallCompliance ? 'COMPLIANT' : 'NON-COMPLIANT';
        const complianceColor = data.overallCompliance ? '#22c55e' : '#ef4444';

        const findingsHtml = data.findings.map((f, i) => `
            <tr>
                <td>${i + 1}</td>
                <td>${f.bmpType}</td>
                <td style="color: ${this.getConditionColor(f.condition)}">${f.condition.toUpperCase()}</td>
                <td>${f.defects.join(', ') || 'None'}</td>
                <td>${f.recommendedAction || '-'}</td>
            </tr>
        `).join('');

        return `
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1 { color: #1e3a5f; }
        .header { border-bottom: 2px solid #1e3a5f; padding-bottom: 20px; }
        .status { font-size: 24px; font-weight: bold; color: ${complianceColor}; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #1e3a5f; color: white; }
        .meta { color: #666; margin: 5px 0; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Stormwater Inspection Report</h1>
        <p class="meta"><strong>Site:</strong> ${data.siteName} (${data.siteId})</p>
        <p class="meta"><strong>Inspector:</strong> ${data.inspectorName}</p>
        <p class="meta"><strong>Date:</strong> ${data.inspectionDate.toLocaleDateString()}</p>
        <p class="meta"><strong>Weather:</strong> ${data.weatherConditions}</p>
        ${data.riskScore !== undefined ? `<p class="meta"><strong>Risk Score:</strong> ${data.riskScore}/100</p>` : ''}
        <p class="status">${complianceStatus}</p>
    </div>
    
    <h2>Inspection Findings</h2>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>BMP Type</th>
                <th>Condition</th>
                <th>Defects</th>
                <th>Recommended Action</th>
            </tr>
        </thead>
        <tbody>
            ${findingsHtml || '<tr><td colspan="5">No findings recorded</td></tr>'}
        </tbody>
    </table>
    
    <div style="margin-top: 40px; border-top: 1px solid #ddd; padding-top: 20px;">
        <p style="color: #666;">Generated by ESCACS Platform on ${new Date().toISOString()}</p>
    </div>
</body>
</html>`;
    }

    /**
     * Build CSV content for Excel
     */
    private buildCsvContent(data: InspectionReportData): string {
        const headers = ['Site ID', 'Site Name', 'Inspector', 'Date', 'Weather', 'Compliance', 'Risk Score', 'BMP Type', 'Condition', 'Defects', 'Recommended Action'];
        const rows = data.findings.map(f => [
            data.siteId,
            data.siteName,
            data.inspectorName,
            data.inspectionDate.toISOString(),
            data.weatherConditions,
            data.overallCompliance ? 'Yes' : 'No',
            data.riskScore?.toString() ?? '',
            f.bmpType,
            f.condition,
            f.defects.join('; '),
            f.recommendedAction ?? '',
        ]);

        return [headers, ...rows].map(row => row.map(cell => `"${cell}"`).join(',')).join('\n');
    }

    /**
     * Get color for condition display
     */
    private getConditionColor(condition: string): string {
        switch (condition) {
            case 'good': return '#22c55e';
            case 'fair': return '#eab308';
            case 'poor': return '#f97316';
            case 'critical': return '#ef4444';
            default: return '#666';
        }
    }
}
